import {
	blackA,
	blackP3A,
	blue,
	blueA,
	blueDark,
	blueDarkA,
	blueDarkP3,
	blueDarkP3A,
	blueP3,
	blueP3A,
	gray,
	grayA,
	grayDark,
	grayDarkA,
	grayDarkP3,
	grayDarkP3A,
	grayP3,
	grayP3A,
	green,
	greenA,
	greenDark,
	greenDarkA,
	greenDarkP3,
	greenDarkP3A,
	greenP3,
	greenP3A,
	mauve,
	mauveA,
	mauveDark,
	mauveDarkA,
	mauveDarkP3,
	mauveDarkP3A,
	mauveP3,
	mauveP3A,
	orange,
	orangeA,
	orangeDark,
	orangeDarkA,
	orangeDarkP3,
	orangeDarkP3A,
	orangeP3,
	orangeP3A,
	pink,
	pinkA,
	pinkDark,
	pinkDarkA,
	pinkDarkP3,
	pinkDarkP3A,
	pinkP3,
	pinkP3A,
	purple,
	purpleA,
	purpleDark,
	purpleDarkA,
	purpleDarkP3,
	purpleDarkP3A,
	purpleP3,
	purpleP3A,
	red,
	redA,
	redDark,
	redDarkA,
	redDarkP3,
	redDarkP3A,
	redP3,
	redP3A,
	whiteA,
	whiteP3A,
	yellow,
	yellowA,
	yellowDark,
	yellowDarkA,
	yellowDarkP3,
	yellowDarkP3A,
	yellowP3,
	yellowP3A,
} from "@radix-ui/colors";

import {
	assignVars,
	createGlobalThemeContract,
	globalStyle,
} from "@vanilla-extract/css";

const colors = createGlobalThemeContract({
	/* grey */
	grey_1: "w-color-grey-1",
	grey_2: "w-color-grey-2",
	grey_3: "w-color-grey-3",
	grey_4: "w-color-grey-4",
	grey_5: "w-color-grey-5",
	grey_6: "w-color-grey-6",
	grey_7: "w-color-grey-7",
	grey_8: "w-color-grey-8",
	grey_9: "w-color-grey-9",
	grey_10: "w-color-grey-10",
	grey_11: "w-color-grey-11",
	grey_12: "w-color-grey-12",
	grey_a1: "w-color-grey-a1",
	grey_a2: "w-color-grey-a2",
	grey_a3: "w-color-grey-a3",
	grey_a4: "w-color-grey-a4",
	grey_a5: "w-color-grey-a5",
	grey_a6: "w-color-grey-a6",
	grey_a7: "w-color-grey-a7",
	grey_a8: "w-color-grey-a8",
	grey_a9: "w-color-grey-a9",
	grey_a10: "w-color-grey-a10",
	grey_a11: "w-color-grey-a11",
	grey_a12: "w-color-grey-a12",

	/* mauve */
	mauve_1: "w-color-mauve-1",
	mauve_2: "w-color-mauve-2",
	mauve_3: "w-color-mauve-3",
	mauve_4: "w-color-mauve-4",
	mauve_5: "w-color-mauve-5",
	mauve_6: "w-color-mauve-6",
	mauve_7: "w-color-mauve-7",
	mauve_8: "w-color-mauve-8",
	mauve_9: "w-color-mauve-9",
	mauve_10: "w-color-mauve-10",
	mauve_11: "w-color-mauve-11",
	mauve_12: "w-color-mauve-12",
	mauve_a1: "w-color-mauve-a1",
	mauve_a2: "w-color-mauve-a2",
	mauve_a3: "w-color-mauve-a3",
	mauve_a4: "w-color-mauve-a4",
	mauve_a5: "w-color-mauve-a5",
	mauve_a6: "w-color-mauve-a6",
	mauve_a7: "w-color-mauve-a7",
	mauve_a8: "w-color-mauve-a8",
	mauve_a9: "w-color-mauve-a9",
	mauve_a10: "w-color-mauve-a10",
	mauve_a11: "w-color-mauve-a11",
	mauve_a12: "w-color-mauve-a12",

	/* red */
	red_1: "w-color-red-1",
	red_2: "w-color-red-2",
	red_3: "w-color-red-3",
	red_4: "w-color-red-4",
	red_5: "w-color-red-5",
	red_6: "w-color-red-6",
	red_7: "w-color-red-7",
	red_8: "w-color-red-8",
	red_9: "w-color-red-9",
	red_10: "w-color-red-10",
	red_11: "w-color-red-11",
	red_12: "w-color-red-12",
	red_a1: "w-color-red-a1",
	red_a2: "w-color-red-a2",
	red_a3: "w-color-red-a3",
	red_a4: "w-color-red-a4",
	red_a5: "w-color-red-a5",
	red_a6: "w-color-red-a6",
	red_a7: "w-color-red-a7",
	red_a8: "w-color-red-a8",
	red_a9: "w-color-red-a9",
	red_a10: "w-color-red-a10",
	red_a11: "w-color-red-a11",
	red_a12: "w-color-red-a12",

	/* orange */
	orange_1: "w-color-orange-1",
	orange_2: "w-color-orange-2",
	orange_3: "w-color-orange-3",
	orange_4: "w-color-orange-4",
	orange_5: "w-color-orange-5",
	orange_6: "w-color-orange-6",
	orange_7: "w-color-orange-7",
	orange_8: "w-color-orange-8",
	orange_9: "w-color-orange-9",
	orange_10: "w-color-orange-10",
	orange_11: "w-color-orange-11",
	orange_12: "w-color-orange-12",
	orange_a1: "w-color-orange-a1",
	orange_a2: "w-color-orange-a2",
	orange_a3: "w-color-orange-a3",
	orange_a4: "w-color-orange-a4",
	orange_a5: "w-color-orange-a5",
	orange_a6: "w-color-orange-a6",
	orange_a7: "w-color-orange-a7",
	orange_a8: "w-color-orange-a8",
	orange_a9: "w-color-orange-a9",
	orange_a10: "w-color-orange-a10",
	orange_a11: "w-color-orange-a11",
	orange_a12: "w-color-orange-a12",

	/* yellow */
	yellow_1: "w-color-yellow-1",
	yellow_2: "w-color-yellow-2",
	yellow_3: "w-color-yellow-3",
	yellow_4: "w-color-yellow-4",
	yellow_5: "w-color-yellow-5",
	yellow_6: "w-color-yellow-6",
	yellow_7: "w-color-yellow-7",
	yellow_8: "w-color-yellow-8",
	yellow_9: "w-color-yellow-9",
	yellow_10: "w-color-yellow-10",
	yellow_11: "w-color-yellow-11",
	yellow_12: "w-color-yellow-12",
	yellow_a1: "w-color-yellow-a1",
	yellow_a2: "w-color-yellow-a2",
	yellow_a3: "w-color-yellow-a3",
	yellow_a4: "w-color-yellow-a4",
	yellow_a5: "w-color-yellow-a5",
	yellow_a6: "w-color-yellow-a6",
	yellow_a7: "w-color-yellow-a7",
	yellow_a8: "w-color-yellow-a8",
	yellow_a9: "w-color-yellow-a9",
	yellow_a10: "w-color-yellow-a10",
	yellow_a11: "w-color-yellow-a11",
	yellow_a12: "w-color-yellow-a12",

	/* green */
	green_1: "w-color-green-1",
	green_2: "w-color-green-2",
	green_3: "w-color-green-3",
	green_4: "w-color-green-4",
	green_5: "w-color-green-5",
	green_6: "w-color-green-6",
	green_7: "w-color-green-7",
	green_8: "w-color-green-8",
	green_9: "w-color-green-9",
	green_10: "w-color-green-10",
	green_11: "w-color-green-11",
	green_12: "w-color-green-12",
	green_a1: "w-color-green-a1",
	green_a2: "w-color-green-a2",
	green_a3: "w-color-green-a3",
	green_a4: "w-color-green-a4",
	green_a5: "w-color-green-a5",
	green_a6: "w-color-green-a6",
	green_a7: "w-color-green-a7",
	green_a8: "w-color-green-a8",
	green_a9: "w-color-green-a9",
	green_a10: "w-color-green-a10",
	green_a11: "w-color-green-a11",
	green_a12: "w-color-green-a12",

	/* blue */
	blue_1: "w-color-blue-1",
	blue_2: "w-color-blue-2",
	blue_3: "w-color-blue-3",
	blue_4: "w-color-blue-4",
	blue_5: "w-color-blue-5",
	blue_6: "w-color-blue-6",
	blue_7: "w-color-blue-7",
	blue_8: "w-color-blue-8",
	blue_9: "w-color-blue-9",
	blue_10: "w-color-blue-10",
	blue_11: "w-color-blue-11",
	blue_12: "w-color-blue-12",
	blue_a1: "w-color-blue-a1",
	blue_a2: "w-color-blue-a2",
	blue_a3: "w-color-blue-a3",
	blue_a4: "w-color-blue-a4",
	blue_a5: "w-color-blue-a5",
	blue_a6: "w-color-blue-a6",
	blue_a7: "w-color-blue-a7",
	blue_a8: "w-color-blue-a8",
	blue_a9: "w-color-blue-a9",
	blue_a10: "w-color-blue-a10",
	blue_a11: "w-color-blue-a11",
	blue_a12: "w-color-blue-a12",

	/* purple */
	purple_1: "w-color-purple-1",
	purple_2: "w-color-purple-2",
	purple_3: "w-color-purple-3",
	purple_4: "w-color-purple-4",
	purple_5: "w-color-purple-5",
	purple_6: "w-color-purple-6",
	purple_7: "w-color-purple-7",
	purple_8: "w-color-purple-8",
	purple_9: "w-color-purple-9",
	purple_10: "w-color-purple-10",
	purple_11: "w-color-purple-11",
	purple_12: "w-color-purple-12",
	purple_a1: "w-color-purple-a1",
	purple_a2: "w-color-purple-a2",
	purple_a3: "w-color-purple-a3",
	purple_a4: "w-color-purple-a4",
	purple_a5: "w-color-purple-a5",
	purple_a6: "w-color-purple-a6",
	purple_a7: "w-color-purple-a7",
	purple_a8: "w-color-purple-a8",
	purple_a9: "w-color-purple-a9",
	purple_a10: "w-color-purple-a10",
	purple_a11: "w-color-purple-a11",
	purple_a12: "w-color-purple-a12",

	/* pink */
	pink_1: "w-color-pink-1",
	pink_2: "w-color-pink-2",
	pink_3: "w-color-pink-3",
	pink_4: "w-color-pink-4",
	pink_5: "w-color-pink-5",
	pink_6: "w-color-pink-6",
	pink_7: "w-color-pink-7",
	pink_8: "w-color-pink-8",
	pink_9: "w-color-pink-9",
	pink_10: "w-color-pink-10",
	pink_11: "w-color-pink-11",
	pink_12: "w-color-pink-12",
	pink_a1: "w-color-pink-a1",
	pink_a2: "w-color-pink-a2",
	pink_a3: "w-color-pink-a3",
	pink_a4: "w-color-pink-a4",
	pink_a5: "w-color-pink-a5",
	pink_a6: "w-color-pink-a6",
	pink_a7: "w-color-pink-a7",
	pink_a8: "w-color-pink-a8",
	pink_a9: "w-color-pink-a9",
	pink_a10: "w-color-pink-a10",
	pink_a11: "w-color-pink-a11",
	pink_a12: "w-color-pink-a12",

	/* black */
	black_a1: "w-color-black-a1",
	black_a2: "w-color-black-a2",
	black_a3: "w-color-black-a3",
	black_a4: "w-color-black-a4",
	black_a5: "w-color-black-a5",
	black_a6: "w-color-black-a6",
	black_a7: "w-color-black-a7",
	black_a8: "w-color-black-a8",
	black_a9: "w-color-black-a9",
	black_a10: "w-color-black-a10",
	black_a11: "w-color-black-a11",
	black_a12: "w-color-black-a12",

	/* white */
	white_a1: "w-color-white-a1",
	white_a2: "w-color-white-a2",
	white_a3: "w-color-white-a3",
	white_a4: "w-color-white-a4",
	white_a5: "w-color-white-a5",
	white_a6: "w-color-white-a6",
	white_a7: "w-color-white-a7",
	white_a8: "w-color-white-a8",
	white_a9: "w-color-white-a9",
	white_a10: "w-color-white-a10",
	white_a11: "w-color-white-a11",
	white_a12: "w-color-white-a12",
});

globalStyle(":root, .light, .light-theme", {
	vars: assignVars(colors, {
		grey_1: gray.gray1,
		grey_2: gray.gray2,
		grey_3: gray.gray3,
		grey_4: gray.gray4,
		grey_5: gray.gray5,
		grey_6: gray.gray6,
		grey_7: gray.gray7,
		grey_8: gray.gray8,
		grey_9: gray.gray9,
		grey_10: gray.gray10,
		grey_11: gray.gray11,
		grey_12: gray.gray12,
		grey_a1: grayA.grayA1,
		grey_a2: grayA.grayA2,
		grey_a3: grayA.grayA3,
		grey_a4: grayA.grayA4,
		grey_a5: grayA.grayA5,
		grey_a6: grayA.grayA6,
		grey_a7: grayA.grayA7,
		grey_a8: grayA.grayA8,
		grey_a9: grayA.grayA9,
		grey_a10: grayA.grayA10,
		grey_a11: grayA.grayA11,
		grey_a12: grayA.grayA12,

		mauve_1: mauve.mauve1,
		mauve_2: mauve.mauve2,
		mauve_3: mauve.mauve3,
		mauve_4: mauve.mauve4,
		mauve_5: mauve.mauve5,
		mauve_6: mauve.mauve6,
		mauve_7: mauve.mauve7,
		mauve_8: mauve.mauve8,
		mauve_9: mauve.mauve9,
		mauve_10: mauve.mauve10,
		mauve_11: mauve.mauve11,
		mauve_12: mauve.mauve12,
		mauve_a1: mauveA.mauveA1,
		mauve_a2: mauveA.mauveA2,
		mauve_a3: mauveA.mauveA3,
		mauve_a4: mauveA.mauveA4,
		mauve_a5: mauveA.mauveA5,
		mauve_a6: mauveA.mauveA6,
		mauve_a7: mauveA.mauveA7,
		mauve_a8: mauveA.mauveA8,
		mauve_a9: mauveA.mauveA9,
		mauve_a10: mauveA.mauveA10,
		mauve_a11: mauveA.mauveA11,
		mauve_a12: mauveA.mauveA12,

		red_1: red.red1,
		red_2: red.red2,
		red_3: red.red3,
		red_4: red.red4,
		red_5: red.red5,
		red_6: red.red6,
		red_7: red.red7,
		red_8: red.red8,
		red_9: red.red9,
		red_10: red.red10,
		red_11: red.red11,
		red_12: red.red12,
		red_a1: redA.redA1,
		red_a2: redA.redA2,
		red_a3: redA.redA3,
		red_a4: redA.redA4,
		red_a5: redA.redA5,
		red_a6: redA.redA6,
		red_a7: redA.redA7,
		red_a8: redA.redA8,
		red_a9: redA.redA9,
		red_a10: redA.redA10,
		red_a11: redA.redA11,
		red_a12: redA.redA12,

		orange_1: orange.orange1,
		orange_2: orange.orange2,
		orange_3: orange.orange3,
		orange_4: orange.orange4,
		orange_5: orange.orange5,
		orange_6: orange.orange6,
		orange_7: orange.orange7,
		orange_8: orange.orange8,
		orange_9: orange.orange9,
		orange_10: orange.orange10,
		orange_11: orange.orange11,
		orange_12: orange.orange12,
		orange_a1: orangeA.orangeA1,
		orange_a2: orangeA.orangeA2,
		orange_a3: orangeA.orangeA3,
		orange_a4: orangeA.orangeA4,
		orange_a5: orangeA.orangeA5,
		orange_a6: orangeA.orangeA6,
		orange_a7: orangeA.orangeA7,
		orange_a8: orangeA.orangeA8,
		orange_a9: orangeA.orangeA9,
		orange_a10: orangeA.orangeA10,
		orange_a11: orangeA.orangeA11,
		orange_a12: orangeA.orangeA12,

		yellow_1: yellow.yellow1,
		yellow_2: yellow.yellow2,
		yellow_3: yellow.yellow3,
		yellow_4: yellow.yellow4,
		yellow_5: yellow.yellow5,
		yellow_6: yellow.yellow6,
		yellow_7: yellow.yellow7,
		yellow_8: yellow.yellow8,
		yellow_9: yellow.yellow9,
		yellow_10: yellow.yellow10,
		yellow_11: yellow.yellow11,
		yellow_12: yellow.yellow12,
		yellow_a1: yellowA.yellowA1,
		yellow_a2: yellowA.yellowA2,
		yellow_a3: yellowA.yellowA3,
		yellow_a4: yellowA.yellowA4,
		yellow_a5: yellowA.yellowA5,
		yellow_a6: yellowA.yellowA6,
		yellow_a7: yellowA.yellowA7,
		yellow_a8: yellowA.yellowA8,
		yellow_a9: yellowA.yellowA9,
		yellow_a10: yellowA.yellowA10,
		yellow_a11: yellowA.yellowA11,
		yellow_a12: yellowA.yellowA12,

		green_1: green.green1,
		green_2: green.green2,
		green_3: green.green3,
		green_4: green.green4,
		green_5: green.green5,
		green_6: green.green6,
		green_7: green.green7,
		green_8: green.green8,
		green_9: green.green9,
		green_10: green.green10,
		green_11: green.green11,
		green_12: green.green12,
		green_a1: greenA.greenA1,
		green_a2: greenA.greenA2,
		green_a3: greenA.greenA3,
		green_a4: greenA.greenA4,
		green_a5: greenA.greenA5,
		green_a6: greenA.greenA6,
		green_a7: greenA.greenA7,
		green_a8: greenA.greenA8,
		green_a9: greenA.greenA9,
		green_a10: greenA.greenA10,
		green_a11: greenA.greenA11,
		green_a12: greenA.greenA12,

		blue_1: blue.blue1,
		blue_2: blue.blue2,
		blue_3: blue.blue3,
		blue_4: blue.blue4,
		blue_5: blue.blue5,
		blue_6: blue.blue6,
		blue_7: blue.blue7,
		blue_8: blue.blue8,
		blue_9: blue.blue9,
		blue_10: blue.blue10,
		blue_11: blue.blue11,
		blue_12: blue.blue12,
		blue_a1: blueA.blueA1,
		blue_a2: blueA.blueA2,
		blue_a3: blueA.blueA3,
		blue_a4: blueA.blueA4,
		blue_a5: blueA.blueA5,
		blue_a6: blueA.blueA6,
		blue_a7: blueA.blueA7,
		blue_a8: blueA.blueA8,
		blue_a9: blueA.blueA9,
		blue_a10: blueA.blueA10,
		blue_a11: blueA.blueA11,
		blue_a12: blueA.blueA12,

		purple_1: purple.purple1,
		purple_2: purple.purple2,
		purple_3: purple.purple3,
		purple_4: purple.purple4,
		purple_5: purple.purple5,
		purple_6: purple.purple6,
		purple_7: purple.purple7,
		purple_8: purple.purple8,
		purple_9: purple.purple9,
		purple_10: purple.purple10,
		purple_11: purple.purple11,
		purple_12: purple.purple12,
		purple_a1: purpleA.purpleA1,
		purple_a2: purpleA.purpleA2,
		purple_a3: purpleA.purpleA3,
		purple_a4: purpleA.purpleA4,
		purple_a5: purpleA.purpleA5,
		purple_a6: purpleA.purpleA6,
		purple_a7: purpleA.purpleA7,
		purple_a8: purpleA.purpleA8,
		purple_a9: purpleA.purpleA9,
		purple_a10: purpleA.purpleA10,
		purple_a11: purpleA.purpleA11,
		purple_a12: purpleA.purpleA12,

		pink_1: pink.pink1,
		pink_2: pink.pink2,
		pink_3: pink.pink3,
		pink_4: pink.pink4,
		pink_5: pink.pink5,
		pink_6: pink.pink6,
		pink_7: pink.pink7,
		pink_8: pink.pink8,
		pink_9: pink.pink9,
		pink_10: pink.pink10,
		pink_11: pink.pink11,
		pink_12: pink.pink12,
		pink_a1: pinkA.pinkA1,
		pink_a2: pinkA.pinkA2,
		pink_a3: pinkA.pinkA3,
		pink_a4: pinkA.pinkA4,
		pink_a5: pinkA.pinkA5,
		pink_a6: pinkA.pinkA6,
		pink_a7: pinkA.pinkA7,
		pink_a8: pinkA.pinkA8,
		pink_a9: pinkA.pinkA9,
		pink_a10: pinkA.pinkA10,
		pink_a11: pinkA.pinkA11,
		pink_a12: pinkA.pinkA12,

		black_a1: blackA.blackA1,
		black_a2: blackA.blackA2,
		black_a3: blackA.blackA3,
		black_a4: blackA.blackA4,
		black_a5: blackA.blackA5,
		black_a6: blackA.blackA6,
		black_a7: blackA.blackA7,
		black_a8: blackA.blackA8,
		black_a9: blackA.blackA9,
		black_a10: blackA.blackA10,
		black_a11: blackA.blackA11,
		black_a12: blackA.blackA12,

		white_a1: whiteA.whiteA1,
		white_a2: whiteA.whiteA2,
		white_a3: whiteA.whiteA3,
		white_a4: whiteA.whiteA4,
		white_a5: whiteA.whiteA5,
		white_a6: whiteA.whiteA6,
		white_a7: whiteA.whiteA7,
		white_a8: whiteA.whiteA8,
		white_a9: whiteA.whiteA9,
		white_a10: whiteA.whiteA10,
		white_a11: whiteA.whiteA11,
		white_a12: whiteA.whiteA12,
	}),
	"@media": {
		"(dynamic-range: high)": {
			"@supports": {
				"(color: color(display-p3 1 1 1))": {
					vars: assignVars(colors, {
						grey_1: grayP3.gray1,
						grey_2: grayP3.gray2,
						grey_3: grayP3.gray3,
						grey_4: grayP3.gray4,
						grey_5: grayP3.gray5,
						grey_6: grayP3.gray6,
						grey_7: grayP3.gray7,
						grey_8: grayP3.gray8,
						grey_9: grayP3.gray9,
						grey_10: grayP3.gray10,
						grey_11: grayP3.gray11,
						grey_12: grayP3.gray12,
						grey_a1: grayP3A.grayA1,
						grey_a2: grayP3A.grayA2,
						grey_a3: grayP3A.grayA3,
						grey_a4: grayP3A.grayA4,
						grey_a5: grayP3A.grayA5,
						grey_a6: grayP3A.grayA6,
						grey_a7: grayP3A.grayA7,
						grey_a8: grayP3A.grayA8,
						grey_a9: grayP3A.grayA9,
						grey_a10: grayP3A.grayA10,
						grey_a11: grayP3A.grayA11,
						grey_a12: grayP3A.grayA12,

						mauve_1: mauveP3.mauve1,
						mauve_2: mauveP3.mauve2,
						mauve_3: mauveP3.mauve3,
						mauve_4: mauveP3.mauve4,
						mauve_5: mauveP3.mauve5,
						mauve_6: mauveP3.mauve6,
						mauve_7: mauveP3.mauve7,
						mauve_8: mauveP3.mauve8,
						mauve_9: mauveP3.mauve9,
						mauve_10: mauveP3.mauve10,
						mauve_11: mauveP3.mauve11,
						mauve_12: mauveP3.mauve12,
						mauve_a1: mauveP3A.mauveA1,
						mauve_a2: mauveP3A.mauveA2,
						mauve_a3: mauveP3A.mauveA3,
						mauve_a4: mauveP3A.mauveA4,
						mauve_a5: mauveP3A.mauveA5,
						mauve_a6: mauveP3A.mauveA6,
						mauve_a7: mauveP3A.mauveA7,
						mauve_a8: mauveP3A.mauveA8,
						mauve_a9: mauveP3A.mauveA9,
						mauve_a10: mauveP3A.mauveA10,
						mauve_a11: mauveP3A.mauveA11,
						mauve_a12: mauveP3A.mauveA12,

						red_1: redP3.red1,
						red_2: redP3.red2,
						red_3: redP3.red3,
						red_4: redP3.red4,
						red_5: redP3.red5,
						red_6: redP3.red6,
						red_7: redP3.red7,
						red_8: redP3.red8,
						red_9: redP3.red9,
						red_10: redP3.red10,
						red_11: redP3.red11,
						red_12: redP3.red12,
						red_a1: redP3A.redA1,
						red_a2: redP3A.redA2,
						red_a3: redP3A.redA3,
						red_a4: redP3A.redA4,
						red_a5: redP3A.redA5,
						red_a6: redP3A.redA6,
						red_a7: redP3A.redA7,
						red_a8: redP3A.redA8,
						red_a9: redP3A.redA9,
						red_a10: redP3A.redA10,
						red_a11: redP3A.redA11,
						red_a12: redP3A.redA12,

						orange_1: orangeP3.orange1,
						orange_2: orangeP3.orange2,
						orange_3: orangeP3.orange3,
						orange_4: orangeP3.orange4,
						orange_5: orangeP3.orange5,
						orange_6: orangeP3.orange6,
						orange_7: orangeP3.orange7,
						orange_8: orangeP3.orange8,
						orange_9: orangeP3.orange9,
						orange_10: orangeP3.orange10,
						orange_11: orangeP3.orange11,
						orange_12: orangeP3.orange12,
						orange_a1: orangeP3A.orangeA1,
						orange_a2: orangeP3A.orangeA2,
						orange_a3: orangeP3A.orangeA3,
						orange_a4: orangeP3A.orangeA4,
						orange_a5: orangeP3A.orangeA5,
						orange_a6: orangeP3A.orangeA6,
						orange_a7: orangeP3A.orangeA7,
						orange_a8: orangeP3A.orangeA8,
						orange_a9: orangeP3A.orangeA9,
						orange_a10: orangeP3A.orangeA10,
						orange_a11: orangeP3A.orangeA11,
						orange_a12: orangeP3A.orangeA12,

						yellow_1: yellowP3.yellow1,
						yellow_2: yellowP3.yellow2,
						yellow_3: yellowP3.yellow3,
						yellow_4: yellowP3.yellow4,
						yellow_5: yellowP3.yellow5,
						yellow_6: yellowP3.yellow6,
						yellow_7: yellowP3.yellow7,
						yellow_8: yellowP3.yellow8,
						yellow_9: yellowP3.yellow9,
						yellow_10: yellowP3.yellow10,
						yellow_11: yellowP3.yellow11,
						yellow_12: yellowP3.yellow12,
						yellow_a1: yellowP3A.yellowA1,
						yellow_a2: yellowP3A.yellowA2,
						yellow_a3: yellowP3A.yellowA3,
						yellow_a4: yellowP3A.yellowA4,
						yellow_a5: yellowP3A.yellowA5,
						yellow_a6: yellowP3A.yellowA6,
						yellow_a7: yellowP3A.yellowA7,
						yellow_a8: yellowP3A.yellowA8,
						yellow_a9: yellowP3A.yellowA9,
						yellow_a10: yellowP3A.yellowA10,
						yellow_a11: yellowP3A.yellowA11,
						yellow_a12: yellowP3A.yellowA12,

						green_1: greenP3.green1,
						green_2: greenP3.green2,
						green_3: greenP3.green3,
						green_4: greenP3.green4,
						green_5: greenP3.green5,
						green_6: greenP3.green6,
						green_7: greenP3.green7,
						green_8: greenP3.green8,
						green_9: greenP3.green9,
						green_10: greenP3.green10,
						green_11: greenP3.green11,
						green_12: greenP3.green12,
						green_a1: greenP3A.greenA1,
						green_a2: greenP3A.greenA2,
						green_a3: greenP3A.greenA3,
						green_a4: greenP3A.greenA4,
						green_a5: greenP3A.greenA5,
						green_a6: greenP3A.greenA6,
						green_a7: greenP3A.greenA7,
						green_a8: greenP3A.greenA8,
						green_a9: greenP3A.greenA9,
						green_a10: greenP3A.greenA10,
						green_a11: greenP3A.greenA11,
						green_a12: greenP3A.greenA12,

						blue_1: blueP3.blue1,
						blue_2: blueP3.blue2,
						blue_3: blueP3.blue3,
						blue_4: blueP3.blue4,
						blue_5: blueP3.blue5,
						blue_6: blueP3.blue6,
						blue_7: blueP3.blue7,
						blue_8: blueP3.blue8,
						blue_9: blueP3.blue9,
						blue_10: blueP3.blue10,
						blue_11: blueP3.blue11,
						blue_12: blueP3.blue12,
						blue_a1: blueP3A.blueA1,
						blue_a2: blueP3A.blueA2,
						blue_a3: blueP3A.blueA3,
						blue_a4: blueP3A.blueA4,
						blue_a5: blueP3A.blueA5,
						blue_a6: blueP3A.blueA6,
						blue_a7: blueP3A.blueA7,
						blue_a8: blueP3A.blueA8,
						blue_a9: blueP3A.blueA9,
						blue_a10: blueP3A.blueA10,
						blue_a11: blueP3A.blueA11,
						blue_a12: blueP3A.blueA12,

						purple_1: purpleP3.purple1,
						purple_2: purpleP3.purple2,
						purple_3: purpleP3.purple3,
						purple_4: purpleP3.purple4,
						purple_5: purpleP3.purple5,
						purple_6: purpleP3.purple6,
						purple_7: purpleP3.purple7,
						purple_8: purpleP3.purple8,
						purple_9: purpleP3.purple9,
						purple_10: purpleP3.purple10,
						purple_11: purpleP3.purple11,
						purple_12: purpleP3.purple12,
						purple_a1: purpleP3A.purpleA1,
						purple_a2: purpleP3A.purpleA2,
						purple_a3: purpleP3A.purpleA3,
						purple_a4: purpleP3A.purpleA4,
						purple_a5: purpleP3A.purpleA5,
						purple_a6: purpleP3A.purpleA6,
						purple_a7: purpleP3A.purpleA7,
						purple_a8: purpleP3A.purpleA8,
						purple_a9: purpleP3A.purpleA9,
						purple_a10: purpleP3A.purpleA10,
						purple_a11: purpleP3A.purpleA11,
						purple_a12: purpleP3A.purpleA12,

						pink_1: pinkP3.pink1,
						pink_2: pinkP3.pink2,
						pink_3: pinkP3.pink3,
						pink_4: pinkP3.pink4,
						pink_5: pinkP3.pink5,
						pink_6: pinkP3.pink6,
						pink_7: pinkP3.pink7,
						pink_8: pinkP3.pink8,
						pink_9: pinkP3.pink9,
						pink_10: pinkP3.pink10,
						pink_11: pinkP3.pink11,
						pink_12: pinkP3.pink12,
						pink_a1: pinkP3A.pinkA1,
						pink_a2: pinkP3A.pinkA2,
						pink_a3: pinkP3A.pinkA3,
						pink_a4: pinkP3A.pinkA4,
						pink_a5: pinkP3A.pinkA5,
						pink_a6: pinkP3A.pinkA6,
						pink_a7: pinkP3A.pinkA7,
						pink_a8: pinkP3A.pinkA8,
						pink_a9: pinkP3A.pinkA9,
						pink_a10: pinkP3A.pinkA10,
						pink_a11: pinkP3A.pinkA11,
						pink_a12: pinkP3A.pinkA12,

						black_a1: blackP3A.blackA1,
						black_a2: blackP3A.blackA2,
						black_a3: blackP3A.blackA3,
						black_a4: blackP3A.blackA4,
						black_a5: blackP3A.blackA5,
						black_a6: blackP3A.blackA6,
						black_a7: blackP3A.blackA7,
						black_a8: blackP3A.blackA8,
						black_a9: blackP3A.blackA9,
						black_a10: blackP3A.blackA10,
						black_a11: blackP3A.blackA11,
						black_a12: blackP3A.blackA12,

						white_a1: whiteP3A.whiteA1,
						white_a2: whiteP3A.whiteA2,
						white_a3: whiteP3A.whiteA3,
						white_a4: whiteP3A.whiteA4,
						white_a5: whiteP3A.whiteA5,
						white_a6: whiteP3A.whiteA6,
						white_a7: whiteP3A.whiteA7,
						white_a8: whiteP3A.whiteA8,
						white_a9: whiteP3A.whiteA9,
						white_a10: whiteP3A.whiteA10,
						white_a11: whiteP3A.whiteA11,
						white_a12: whiteP3A.whiteA12,
					}),
				},
			},
		},
	},
});

globalStyle(":root, .dark, .dark-theme", {
	vars: assignVars(colors, {
		grey_1: grayDark.gray1,
		grey_2: grayDark.gray2,
		grey_3: grayDark.gray3,
		grey_4: grayDark.gray4,
		grey_5: grayDark.gray5,
		grey_6: grayDark.gray6,
		grey_7: grayDark.gray7,
		grey_8: grayDark.gray8,
		grey_9: grayDark.gray9,
		grey_10: grayDark.gray10,
		grey_11: grayDark.gray11,
		grey_12: grayDark.gray12,
		grey_a1: grayDarkA.grayA1,
		grey_a2: grayDarkA.grayA2,
		grey_a3: grayDarkA.grayA3,
		grey_a4: grayDarkA.grayA4,
		grey_a5: grayDarkA.grayA5,
		grey_a6: grayDarkA.grayA6,
		grey_a7: grayDarkA.grayA7,
		grey_a8: grayDarkA.grayA8,
		grey_a9: grayDarkA.grayA9,
		grey_a10: grayDarkA.grayA10,
		grey_a11: grayDarkA.grayA11,
		grey_a12: grayDarkA.grayA12,

		mauve_1: mauveDark.mauve1,
		mauve_2: mauveDark.mauve2,
		mauve_3: mauveDark.mauve3,
		mauve_4: mauveDark.mauve4,
		mauve_5: mauveDark.mauve5,
		mauve_6: mauveDark.mauve6,
		mauve_7: mauveDark.mauve7,
		mauve_8: mauveDark.mauve8,
		mauve_9: mauveDark.mauve9,
		mauve_10: mauveDark.mauve10,
		mauve_11: mauveDark.mauve11,
		mauve_12: mauveDark.mauve12,
		mauve_a1: mauveDarkA.mauveA1,
		mauve_a2: mauveDarkA.mauveA2,
		mauve_a3: mauveDarkA.mauveA3,
		mauve_a4: mauveDarkA.mauveA4,
		mauve_a5: mauveDarkA.mauveA5,
		mauve_a6: mauveDarkA.mauveA6,
		mauve_a7: mauveDarkA.mauveA7,
		mauve_a8: mauveDarkA.mauveA8,
		mauve_a9: mauveDarkA.mauveA9,
		mauve_a10: mauveDarkA.mauveA10,
		mauve_a11: mauveDarkA.mauveA11,
		mauve_a12: mauveDarkA.mauveA12,

		red_1: redDark.red1,
		red_2: redDark.red2,
		red_3: redDark.red3,
		red_4: redDark.red4,
		red_5: redDark.red5,
		red_6: redDark.red6,
		red_7: redDark.red7,
		red_8: redDark.red8,
		red_9: redDark.red9,
		red_10: redDark.red10,
		red_11: redDark.red11,
		red_12: redDark.red12,
		red_a1: redDarkA.redA1,
		red_a2: redDarkA.redA2,
		red_a3: redDarkA.redA3,
		red_a4: redDarkA.redA4,
		red_a5: redDarkA.redA5,
		red_a6: redDarkA.redA6,
		red_a7: redDarkA.redA7,
		red_a8: redDarkA.redA8,
		red_a9: redDarkA.redA9,
		red_a10: redDarkA.redA10,
		red_a11: redDarkA.redA11,
		red_a12: redDarkA.redA12,

		orange_1: orangeDark.orange1,
		orange_2: orangeDark.orange2,
		orange_3: orangeDark.orange3,
		orange_4: orangeDark.orange4,
		orange_5: orangeDark.orange5,
		orange_6: orangeDark.orange6,
		orange_7: orangeDark.orange7,
		orange_8: orangeDark.orange8,
		orange_9: orangeDark.orange9,
		orange_10: orangeDark.orange10,
		orange_11: orangeDark.orange11,
		orange_12: orangeDark.orange12,
		orange_a1: orangeDarkA.orangeA1,
		orange_a2: orangeDarkA.orangeA2,
		orange_a3: orangeDarkA.orangeA3,
		orange_a4: orangeDarkA.orangeA4,
		orange_a5: orangeDarkA.orangeA5,
		orange_a6: orangeDarkA.orangeA6,
		orange_a7: orangeDarkA.orangeA7,
		orange_a8: orangeDarkA.orangeA8,
		orange_a9: orangeDarkA.orangeA9,
		orange_a10: orangeDarkA.orangeA10,
		orange_a11: orangeDarkA.orangeA11,
		orange_a12: orangeDarkA.orangeA12,

		yellow_1: yellowDark.yellow1,
		yellow_2: yellowDark.yellow2,
		yellow_3: yellowDark.yellow3,
		yellow_4: yellowDark.yellow4,
		yellow_5: yellowDark.yellow5,
		yellow_6: yellowDark.yellow6,
		yellow_7: yellowDark.yellow7,
		yellow_8: yellowDark.yellow8,
		yellow_9: yellowDark.yellow9,
		yellow_10: yellowDark.yellow10,
		yellow_11: yellowDark.yellow11,
		yellow_12: yellowDark.yellow12,
		yellow_a1: yellowDarkA.yellowA1,
		yellow_a2: yellowDarkA.yellowA2,
		yellow_a3: yellowDarkA.yellowA3,
		yellow_a4: yellowDarkA.yellowA4,
		yellow_a5: yellowDarkA.yellowA5,
		yellow_a6: yellowDarkA.yellowA6,
		yellow_a7: yellowDarkA.yellowA7,
		yellow_a8: yellowDarkA.yellowA8,
		yellow_a9: yellowDarkA.yellowA9,
		yellow_a10: yellowDarkA.yellowA10,
		yellow_a11: yellowDarkA.yellowA11,
		yellow_a12: yellowDarkA.yellowA12,

		green_1: greenDark.green1,
		green_2: greenDark.green2,
		green_3: greenDark.green3,
		green_4: greenDark.green4,
		green_5: greenDark.green5,
		green_6: greenDark.green6,
		green_7: greenDark.green7,
		green_8: greenDark.green8,
		green_9: greenDark.green9,
		green_10: greenDark.green10,
		green_11: greenDark.green11,
		green_12: greenDark.green12,
		green_a1: greenDarkA.greenA1,
		green_a2: greenDarkA.greenA2,
		green_a3: greenDarkA.greenA3,
		green_a4: greenDarkA.greenA4,
		green_a5: greenDarkA.greenA5,
		green_a6: greenDarkA.greenA6,
		green_a7: greenDarkA.greenA7,
		green_a8: greenDarkA.greenA8,
		green_a9: greenDarkA.greenA9,
		green_a10: greenDarkA.greenA10,
		green_a11: greenDarkA.greenA11,
		green_a12: greenDarkA.greenA12,

		blue_1: blueDark.blue1,
		blue_2: blueDark.blue2,
		blue_3: blueDark.blue3,
		blue_4: blueDark.blue4,
		blue_5: blueDark.blue5,
		blue_6: blueDark.blue6,
		blue_7: blueDark.blue7,
		blue_8: blueDark.blue8,
		blue_9: blueDark.blue9,
		blue_10: blueDark.blue10,
		blue_11: blueDark.blue11,
		blue_12: blueDark.blue12,
		blue_a1: blueDarkA.blueA1,
		blue_a2: blueDarkA.blueA2,
		blue_a3: blueDarkA.blueA3,
		blue_a4: blueDarkA.blueA4,
		blue_a5: blueDarkA.blueA5,
		blue_a6: blueDarkA.blueA6,
		blue_a7: blueDarkA.blueA7,
		blue_a8: blueDarkA.blueA8,
		blue_a9: blueDarkA.blueA9,
		blue_a10: blueDarkA.blueA10,
		blue_a11: blueDarkA.blueA11,
		blue_a12: blueDarkA.blueA12,

		purple_1: purpleDark.purple1,
		purple_2: purpleDark.purple2,
		purple_3: purpleDark.purple3,
		purple_4: purpleDark.purple4,
		purple_5: purpleDark.purple5,
		purple_6: purpleDark.purple6,
		purple_7: purpleDark.purple7,
		purple_8: purpleDark.purple8,
		purple_9: purpleDark.purple9,
		purple_10: purpleDark.purple10,
		purple_11: purpleDark.purple11,
		purple_12: purpleDark.purple12,
		purple_a1: purpleDarkA.purpleA1,
		purple_a2: purpleDarkA.purpleA2,
		purple_a3: purpleDarkA.purpleA3,
		purple_a4: purpleDarkA.purpleA4,
		purple_a5: purpleDarkA.purpleA5,
		purple_a6: purpleDarkA.purpleA6,
		purple_a7: purpleDarkA.purpleA7,
		purple_a8: purpleDarkA.purpleA8,
		purple_a9: purpleDarkA.purpleA9,
		purple_a10: purpleDarkA.purpleA10,
		purple_a11: purpleDarkA.purpleA11,
		purple_a12: purpleDarkA.purpleA12,

		pink_1: pinkDark.pink1,
		pink_2: pinkDark.pink2,
		pink_3: pinkDark.pink3,
		pink_4: pinkDark.pink4,
		pink_5: pinkDark.pink5,
		pink_6: pinkDark.pink6,
		pink_7: pinkDark.pink7,
		pink_8: pinkDark.pink8,
		pink_9: pinkDark.pink9,
		pink_10: pinkDark.pink10,
		pink_11: pinkDark.pink11,
		pink_12: pinkDark.pink12,
		pink_a1: pinkDarkA.pinkA1,
		pink_a2: pinkDarkA.pinkA2,
		pink_a3: pinkDarkA.pinkA3,
		pink_a4: pinkDarkA.pinkA4,
		pink_a5: pinkDarkA.pinkA5,
		pink_a6: pinkDarkA.pinkA6,
		pink_a7: pinkDarkA.pinkA7,
		pink_a8: pinkDarkA.pinkA8,
		pink_a9: pinkDarkA.pinkA9,
		pink_a10: pinkDarkA.pinkA10,
		pink_a11: pinkDarkA.pinkA11,
		pink_a12: pinkDarkA.pinkA12,

		black_a1: blackA.blackA1,
		black_a2: blackA.blackA2,
		black_a3: blackA.blackA3,
		black_a4: blackA.blackA4,
		black_a5: blackA.blackA5,
		black_a6: blackA.blackA6,
		black_a7: blackA.blackA7,
		black_a8: blackA.blackA8,
		black_a9: blackA.blackA9,
		black_a10: blackA.blackA10,
		black_a11: blackA.blackA11,
		black_a12: blackA.blackA12,

		white_a1: whiteA.whiteA1,
		white_a2: whiteA.whiteA2,
		white_a3: whiteA.whiteA3,
		white_a4: whiteA.whiteA4,
		white_a5: whiteA.whiteA5,
		white_a6: whiteA.whiteA6,
		white_a7: whiteA.whiteA7,
		white_a8: whiteA.whiteA8,
		white_a9: whiteA.whiteA9,
		white_a10: whiteA.whiteA10,
		white_a11: whiteA.whiteA11,
		white_a12: whiteA.whiteA12,
	}),
	"@media": {
		"(dynamic-range: high)": {
			"@supports": {
				"(color: color(display-p3 1 1 1))": {
					vars: assignVars(colors, {
						grey_1: grayDarkP3.gray1,
						grey_2: grayDarkP3.gray2,
						grey_3: grayDarkP3.gray3,
						grey_4: grayDarkP3.gray4,
						grey_5: grayDarkP3.gray5,
						grey_6: grayDarkP3.gray6,
						grey_7: grayDarkP3.gray7,
						grey_8: grayDarkP3.gray8,
						grey_9: grayDarkP3.gray9,
						grey_10: grayDarkP3.gray10,
						grey_11: grayDarkP3.gray11,
						grey_12: grayDarkP3.gray12,
						grey_a1: grayDarkP3A.grayA1,
						grey_a2: grayDarkP3A.grayA2,
						grey_a3: grayDarkP3A.grayA3,
						grey_a4: grayDarkP3A.grayA4,
						grey_a5: grayDarkP3A.grayA5,
						grey_a6: grayDarkP3A.grayA6,
						grey_a7: grayDarkP3A.grayA7,
						grey_a8: grayDarkP3A.grayA8,
						grey_a9: grayDarkP3A.grayA9,
						grey_a10: grayDarkP3A.grayA10,
						grey_a11: grayDarkP3A.grayA11,
						grey_a12: grayDarkP3A.grayA12,

						mauve_1: mauveDarkP3.mauve1,
						mauve_2: mauveDarkP3.mauve2,
						mauve_3: mauveDarkP3.mauve3,
						mauve_4: mauveDarkP3.mauve4,
						mauve_5: mauveDarkP3.mauve5,
						mauve_6: mauveDarkP3.mauve6,
						mauve_7: mauveDarkP3.mauve7,
						mauve_8: mauveDarkP3.mauve8,
						mauve_9: mauveDarkP3.mauve9,
						mauve_10: mauveDarkP3.mauve10,
						mauve_11: mauveDarkP3.mauve11,
						mauve_12: mauveDarkP3.mauve12,
						mauve_a1: mauveDarkP3A.mauveA1,
						mauve_a2: mauveDarkP3A.mauveA2,
						mauve_a3: mauveDarkP3A.mauveA3,
						mauve_a4: mauveDarkP3A.mauveA4,
						mauve_a5: mauveDarkP3A.mauveA5,
						mauve_a6: mauveDarkP3A.mauveA6,
						mauve_a7: mauveDarkP3A.mauveA7,
						mauve_a8: mauveDarkP3A.mauveA8,
						mauve_a9: mauveDarkP3A.mauveA9,
						mauve_a10: mauveDarkP3A.mauveA10,
						mauve_a11: mauveDarkP3A.mauveA11,
						mauve_a12: mauveDarkP3A.mauveA12,

						red_1: redDarkP3.red1,
						red_2: redDarkP3.red2,
						red_3: redDarkP3.red3,
						red_4: redDarkP3.red4,
						red_5: redDarkP3.red5,
						red_6: redDarkP3.red6,
						red_7: redDarkP3.red7,
						red_8: redDarkP3.red8,
						red_9: redDarkP3.red9,
						red_10: redDarkP3.red10,
						red_11: redDarkP3.red11,
						red_12: redDarkP3.red12,
						red_a1: redDarkP3A.redA1,
						red_a2: redDarkP3A.redA2,
						red_a3: redDarkP3A.redA3,
						red_a4: redDarkP3A.redA4,
						red_a5: redDarkP3A.redA5,
						red_a6: redDarkP3A.redA6,
						red_a7: redDarkP3A.redA7,
						red_a8: redDarkP3A.redA8,
						red_a9: redDarkP3A.redA9,
						red_a10: redDarkP3A.redA10,
						red_a11: redDarkP3A.redA11,
						red_a12: redDarkP3A.redA12,

						orange_1: orangeDarkP3.orange1,
						orange_2: orangeDarkP3.orange2,
						orange_3: orangeDarkP3.orange3,
						orange_4: orangeDarkP3.orange4,
						orange_5: orangeDarkP3.orange5,
						orange_6: orangeDarkP3.orange6,
						orange_7: orangeDarkP3.orange7,
						orange_8: orangeDarkP3.orange8,
						orange_9: orangeDarkP3.orange9,
						orange_10: orangeDarkP3.orange10,
						orange_11: orangeDarkP3.orange11,
						orange_12: orangeDarkP3.orange12,
						orange_a1: orangeDarkP3A.orangeA1,
						orange_a2: orangeDarkP3A.orangeA2,
						orange_a3: orangeDarkP3A.orangeA3,
						orange_a4: orangeDarkP3A.orangeA4,
						orange_a5: orangeDarkP3A.orangeA5,
						orange_a6: orangeDarkP3A.orangeA6,
						orange_a7: orangeDarkP3A.orangeA7,
						orange_a8: orangeDarkP3A.orangeA8,
						orange_a9: orangeDarkP3A.orangeA9,
						orange_a10: orangeDarkP3A.orangeA10,
						orange_a11: orangeDarkP3A.orangeA11,
						orange_a12: orangeDarkP3A.orangeA12,

						yellow_1: yellowDarkP3.yellow1,
						yellow_2: yellowDarkP3.yellow2,
						yellow_3: yellowDarkP3.yellow3,
						yellow_4: yellowDarkP3.yellow4,
						yellow_5: yellowDarkP3.yellow5,
						yellow_6: yellowDarkP3.yellow6,
						yellow_7: yellowDarkP3.yellow7,
						yellow_8: yellowDarkP3.yellow8,
						yellow_9: yellowDarkP3.yellow9,
						yellow_10: yellowDarkP3.yellow10,
						yellow_11: yellowDarkP3.yellow11,
						yellow_12: yellowDarkP3.yellow12,
						yellow_a1: yellowDarkP3A.yellowA1,
						yellow_a2: yellowDarkP3A.yellowA2,
						yellow_a3: yellowDarkP3A.yellowA3,
						yellow_a4: yellowDarkP3A.yellowA4,
						yellow_a5: yellowDarkP3A.yellowA5,
						yellow_a6: yellowDarkP3A.yellowA6,
						yellow_a7: yellowDarkP3A.yellowA7,
						yellow_a8: yellowDarkP3A.yellowA8,
						yellow_a9: yellowDarkP3A.yellowA9,
						yellow_a10: yellowDarkP3A.yellowA10,
						yellow_a11: yellowDarkP3A.yellowA11,
						yellow_a12: yellowDarkP3A.yellowA12,

						green_1: greenDarkP3.green1,
						green_2: greenDarkP3.green2,
						green_3: greenDarkP3.green3,
						green_4: greenDarkP3.green4,
						green_5: greenDarkP3.green5,
						green_6: greenDarkP3.green6,
						green_7: greenDarkP3.green7,
						green_8: greenDarkP3.green8,
						green_9: greenDarkP3.green9,
						green_10: greenDarkP3.green10,
						green_11: greenDarkP3.green11,
						green_12: greenDarkP3.green12,
						green_a1: greenDarkP3A.greenA1,
						green_a2: greenDarkP3A.greenA2,
						green_a3: greenDarkP3A.greenA3,
						green_a4: greenDarkP3A.greenA4,
						green_a5: greenDarkP3A.greenA5,
						green_a6: greenDarkP3A.greenA6,
						green_a7: greenDarkP3A.greenA7,
						green_a8: greenDarkP3A.greenA8,
						green_a9: greenDarkP3A.greenA9,
						green_a10: greenDarkP3A.greenA10,
						green_a11: greenDarkP3A.greenA11,
						green_a12: greenDarkP3A.greenA12,

						blue_1: blueDarkP3.blue1,
						blue_2: blueDarkP3.blue2,
						blue_3: blueDarkP3.blue3,
						blue_4: blueDarkP3.blue4,
						blue_5: blueDarkP3.blue5,
						blue_6: blueDarkP3.blue6,
						blue_7: blueDarkP3.blue7,
						blue_8: blueDarkP3.blue8,
						blue_9: blueDarkP3.blue9,
						blue_10: blueDarkP3.blue10,
						blue_11: blueDarkP3.blue11,
						blue_12: blueDarkP3.blue12,
						blue_a1: blueDarkP3A.blueA1,
						blue_a2: blueDarkP3A.blueA2,
						blue_a3: blueDarkP3A.blueA3,
						blue_a4: blueDarkP3A.blueA4,
						blue_a5: blueDarkP3A.blueA5,
						blue_a6: blueDarkP3A.blueA6,
						blue_a7: blueDarkP3A.blueA7,
						blue_a8: blueDarkP3A.blueA8,
						blue_a9: blueDarkP3A.blueA9,
						blue_a10: blueDarkP3A.blueA10,
						blue_a11: blueDarkP3A.blueA11,
						blue_a12: blueDarkP3A.blueA12,

						purple_1: purpleDarkP3.purple1,
						purple_2: purpleDarkP3.purple2,
						purple_3: purpleDarkP3.purple3,
						purple_4: purpleDarkP3.purple4,
						purple_5: purpleDarkP3.purple5,
						purple_6: purpleDarkP3.purple6,
						purple_7: purpleDarkP3.purple7,
						purple_8: purpleDarkP3.purple8,
						purple_9: purpleDarkP3.purple9,
						purple_10: purpleDarkP3.purple10,
						purple_11: purpleDarkP3.purple11,
						purple_12: purpleDarkP3.purple12,
						purple_a1: purpleDarkP3A.purpleA1,
						purple_a2: purpleDarkP3A.purpleA2,
						purple_a3: purpleDarkP3A.purpleA3,
						purple_a4: purpleDarkP3A.purpleA4,
						purple_a5: purpleDarkP3A.purpleA5,
						purple_a6: purpleDarkP3A.purpleA6,
						purple_a7: purpleDarkP3A.purpleA7,
						purple_a8: purpleDarkP3A.purpleA8,
						purple_a9: purpleDarkP3A.purpleA9,
						purple_a10: purpleDarkP3A.purpleA10,
						purple_a11: purpleDarkP3A.purpleA11,
						purple_a12: purpleDarkP3A.purpleA12,

						pink_1: pinkDarkP3.pink1,
						pink_2: pinkDarkP3.pink2,
						pink_3: pinkDarkP3.pink3,
						pink_4: pinkDarkP3.pink4,
						pink_5: pinkDarkP3.pink5,
						pink_6: pinkDarkP3.pink6,
						pink_7: pinkDarkP3.pink7,
						pink_8: pinkDarkP3.pink8,
						pink_9: pinkDarkP3.pink9,
						pink_10: pinkDarkP3.pink10,
						pink_11: pinkDarkP3.pink11,
						pink_12: pinkDarkP3.pink12,
						pink_a1: pinkDarkP3A.pinkA1,
						pink_a2: pinkDarkP3A.pinkA2,
						pink_a3: pinkDarkP3A.pinkA3,
						pink_a4: pinkDarkP3A.pinkA4,
						pink_a5: pinkDarkP3A.pinkA5,
						pink_a6: pinkDarkP3A.pinkA6,
						pink_a7: pinkDarkP3A.pinkA7,
						pink_a8: pinkDarkP3A.pinkA8,
						pink_a9: pinkDarkP3A.pinkA9,
						pink_a10: pinkDarkP3A.pinkA10,
						pink_a11: pinkDarkP3A.pinkA11,
						pink_a12: pinkDarkP3A.pinkA12,

						black_a1: blackP3A.blackA1,
						black_a2: blackP3A.blackA2,
						black_a3: blackP3A.blackA3,
						black_a4: blackP3A.blackA4,
						black_a5: blackP3A.blackA5,
						black_a6: blackP3A.blackA6,
						black_a7: blackP3A.blackA7,
						black_a8: blackP3A.blackA8,
						black_a9: blackP3A.blackA9,
						black_a10: blackP3A.blackA10,
						black_a11: blackP3A.blackA11,
						black_a12: blackP3A.blackA12,

						white_a1: whiteP3A.whiteA1,
						white_a2: whiteP3A.whiteA2,
						white_a3: whiteP3A.whiteA3,
						white_a4: whiteP3A.whiteA4,
						white_a5: whiteP3A.whiteA5,
						white_a6: whiteP3A.whiteA6,
						white_a7: whiteP3A.whiteA7,
						white_a8: whiteP3A.whiteA8,
						white_a9: whiteP3A.whiteA9,
						white_a10: whiteP3A.whiteA10,
						white_a11: whiteP3A.whiteA11,
						white_a12: whiteP3A.whiteA12,
					}),
				},
			},
		},
	},
});
